steps:
  # Install dependencies
  - name: 'python:3.9'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt', '--user']

  # Deploy to Cloud Functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'functions'
      - 'deploy'
      - 'excel-pptx-merger'
      - '--gen2'
      - '--runtime=python39'
      - '--region=${_REGION}'
      - '--source=.'
      - '--entry-point=excel_pptx_merger'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--memory=1024MB'
      - '--timeout=540s'
      - '--set-env-vars=STORAGE_BACKEND=GCS,GCS_BUCKET_NAME=${_BUCKET_NAME},GCS_BASE_PREFIX=${_BASE_PREFIX},API_KEY=${_API_KEY}'

substitutions:
  _REGION: us-central1
  _BUCKET_NAME: excel-pptx-merger-storage
  _BASE_PREFIX: temp
  _API_KEY: changeme-in-production

options:
  logging: CLOUD_LOGGING_ONLY
